spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: vCHjKAGhplwtbgke7fss4HgO9
            client-secret: TSdPkZmmvqQVTs1R1fXsLi7kzxLfdS7IlDZsmJESGF3pQikHqq
            authorization-grant-type: 'authorization_code'
            redirect-uri: 'http://localhost:8080/callback.html'
            scope: [ 'openid', 'profile', 'email' ]
        provider:
          auth0:
            issuer-uri: http://localhost:8080